In [1]:
import numpy as np

In [33]:
x = np.array([1,2,3,4], dtype=np.complex64)
y = x
z = x + y
print(z)

[2.+0.j 4.+0.j 6.+0.j 8.+0.j]


In [34]:
type(x)

numpy.ndarray

In [35]:
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [36]:
X = np.array([[1,2],[3,4]])
Y = np.array([[1,2],[3,4]])
Z = np.matmul(X, Y)
print(X)
print(Y)
print(Z)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]]
